name: Provision ATP

on: 
  #push:
    #branches:
      #- main
  issues:
    types: [opened, reopened]    
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      OCI_CLI_USER: ${{ secrets.TF_VAR_USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.TF_VAR_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.TF_VAR_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.TF_VAR_PRIVATE_KEY }}
      OCI_CLI_REGION: ${{ secrets.TF_VAR_REGION }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v2
          
      - run: |
         terraform -v 

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -reconfigure -backend-config="address=${{ secrets.TF_BACKEND_CONFIG }}"
        working-directory: "./src/main/resources/db/tf/modules/atp"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - uses: schdck/create-env-json@v1
        id: create-env
        with:
          file-name: './src/main/resources/db/tf/modules/atp/env.json'
          TENANCY_OCID: ${{ secrets.TF_VAR_TENANCY_OCID }}
          USER_OCID: ${{ secrets.TF_VAR_USER_OCID }}
          FINGERPRINT: ${{ secrets.TF_VAR_FINGERPRINT }}
          PRIVATE_KEY: ${{ secrets.TF_VAR_PRIVATE_KEY }}
          REGION: ${{ secrets.TF_VAR_REGION }}
          COMPARTMENT_OCID: ${{ secrets.TF_VAR_COMPARTMENT_OCID }}
          DB_NAME: ${{ secrets.TF_VAR_DB_NAME }}
          ADMIN_PASSWORD: ${{ secrets.TF_VAR_ADMIN_PASSWORD }}
          DB_VERSION: ${{ secrets.TF_VAR_DB_VERSION }}
          DB_WORKLOAD: ${{ secrets.TF_VAR_DB_WORKLOAD }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=env.json -out myplan -no-color
        working-directory: "./src/main/resources/db/tf/modules/atp"

      - name: Terraform Apply
        #if: "contains(github.event.head_commit.message, 'apply')"
        if: contains(github.event.issue.title, 'create-atp') 
        id: apply
        run: terraform apply -input=false -auto-approve myplan
        working-directory: "./src/main/resources/db/tf/modules/atp"
        
      - name: Install OCI CLI
        if: contains(github.event.issue.title, 'create-atp') 
        uses: oracle-actions/run-oci-cli-command@v1.0
        id: oci-cli
        with:
          command: 'iam region list'
          #query: 'data[0]'
          
      - name: Get ATP url with OCI CLI
        if: contains(github.event.issue.title, 'create-atp')
        id: find-atp-url 
        run: echo "::set-output name=ATP_URL::$(oci db autonomous-database list --compartment-id=${{ secrets.TF_VAR_COMPARTMENT_OCID }} --display-name=${{ secrets.TF_VAR_DB_NAME }} --lifecycle-state=AVAILABLE | jq -r .data[0].\"connection-strings\".\"profiles\"[0].value)"
          
      - name: show ATP url
        if: contains(github.event.issue.title, 'create-atp') 
        run: |
         echo "${{ steps.find-atp-url.outputs.ATP_URL }}"  
         
      - name: 'Set up latest Oracle JDK 17'
        if: contains(github.event.issue.title, 'create-atp') 
        uses: oracle-actions/setup-java@v1
        with:
         website: oracle.com
         release: 17    
         
      - name: Install Oracle Sqlcl
        if: contains(github.event.issue.title, 'create-atp') 
        uses: cpruvost/setup-sqlcl@v1.0.0   
        
      - name: Create Oracle Schema
        if: contains(github.event.issue.title, 'create-atp') 
        run: |
          /sqlcl/bin/sql -V
          sed 's/mypassword/${{ secrets.TF_VAR_ADMIN_PASSWORD }}/g' ./src/main/resources/db/sql/create-schema.sql
          cat ./src/main/resources/db/sql/create-schema.sql

      - name: Terraform Destroy
        #if: "contains(github.event.head_commit.message, 'destroy')"
        if: contains(github.event.issue.title, 'destroy-atp') 
        id: destroy
        run: terraform destroy -auto-approve  
        working-directory: "./src/main/resources/db/tf/modules/atp"

         
        